[openai]
api_key = '2FT6hvviWx3UHRmLJaIan6opXivnThDbzFnNvNgP1U1llarGbGRcJQQJ99BEACYeBjFXJ3w3AAABACOGeaAh'
api_version = "2024-12-01-preview"
endpoint = "https://ai-based-work.openai.azure.com/"
deployment = "gpt-4o"

[email]
address = 'rajat.contact.rajat@gmail.com'
password =  'hojr dvyi etuz azxp' 
smtp_server = "smtp.gmail.com"
smtp_port = 465
